name: Commit message checker

on: [push,pull_request]

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pytest
    - name: Self-test
      run: pytest ci/test_commit_message_checker.py
    - name: Check commit messages
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: python ./ci/check_commit_message.py